version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "ziad"
      MYSQL_PASSWORD: "aezakmi"
      MYSQL_ROOT_PASSWORD: "aezakmi"
    ports:

      - '3000:3306'
    volumes:
      - my-db:/var/lib/mysql
  my-app:
    depends_on:
      - db
    restart: on-failure
    links:
      - "db:db"
    environment:
      MYSQL_HOST: "db"
      MYSQL_USERNAME: "ziad"
      MYSQL_PASSWORD: "aezakmi"
      MYSQL_DB: "test"
    build:
      context:  .
      dockerfile: Dockerfile

    image: maha-task
    ports:
      - "8080:8080"

volumes:
  my-db:
